[GridOptimizationChallenge]
git-tree-sha1 = "c93fe411bf68e73c2ca4d9c9c5cd7703428632b4"

    [[GridOptimizationChallenge.download]]
    sha256 = "a730b0299b745c3c0bd106046146c45742be1bba48971fd6affb5811be451fd8"
    url = "https://github.com/jbarberia/GridOptimizationChallengeCases/archive/refs/tags/v1.0.tar.gz"
